export const STORAGE_KEYS = {
  SESSION: "ZAPH_SESSION",
  CIRCLE_ID: "ZAPH_CIRCLE_ID",
  CIRCLE_CODE: "ZAPH_CIRCLE_CODE",
  CIRCLE_DIFFICULTY: "ZAPH_CIRCLE_DIFFICULTY",
  CIRCLE_NAME: "ZAPH_CIRCLE_NAME",
  FIRST_NAME: "ZAPH_FIRST_NAME",
  MOTIVATION_TIER: "ZAPH_MOTIVATION_TIER",
  SUGGESTED_CATEGORIES: "ZAPH_SUGGESTED_CATEGORIES",
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
